// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ControllerInterface is an autogenerated mock type for the ControllerInterface type
type ControllerInterface struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields:
func (_m *ControllerInterface) CreateTask() func(*gin.Context) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}

// DeleteTask provides a mock function with given fields:
func (_m *ControllerInterface) DeleteTask() func(*gin.Context) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}

// GetTasks provides a mock function with given fields:
func (_m *ControllerInterface) GetTasks() func(*gin.Context) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}

// GetTasksId provides a mock function with given fields:
func (_m *ControllerInterface) GetTasksId() func(*gin.Context) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTasksId")
	}

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}

// UpdateTask provides a mock function with given fields:
func (_m *ControllerInterface) UpdateTask() func(*gin.Context) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}

// NewControllerInterface creates a new instance of ControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewControllerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ControllerInterface {
	mock := &ControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
