// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zaahidali/task_manager_api/Domain"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// TaskUseCaseInterface is an autogenerated mock type for the TaskUseCaseInterface type
type TaskUseCaseInterface struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: task
func (_m *TaskUseCaseInterface) CreateTask(task domain.Task) (interface{}, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Task) (interface{}, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(domain.Task) interface{}); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(domain.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: id
func (_m *TaskUseCaseInterface) DeleteTask(id primitive.ObjectID) (interface{}, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) (interface{}, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) interface{}); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlltasks provides a mock function with given fields:
func (_m *TaskUseCaseInterface) GetAlltasks() ([]domain.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAlltasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSpecificTask provides a mock function with given fields: id
func (_m *TaskUseCaseInterface) GetSpecificTask(id primitive.ObjectID) (domain.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSpecificTask")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) (domain.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) domain.Task); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: id, task
func (_m *TaskUseCaseInterface) UpdateTask(id primitive.ObjectID, task domain.Task) (interface{}, error) {
	ret := _m.Called(id, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, domain.Task) (interface{}, error)); ok {
		return rf(id, task)
	}
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, domain.Task) interface{}); ok {
		r0 = rf(id, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(primitive.ObjectID, domain.Task) error); ok {
		r1 = rf(id, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskUseCaseInterface creates a new instance of TaskUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUseCaseInterface {
	mock := &TaskUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
