name: Go CI

on:
  push:
    branches: [ auth-aoth ]
  pull_request:
    branches: [ auth-aoth ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'  # Ensure this matches your go.mod

    - name: Build
      run: go build -v ./...

    - name: Run tests
      env:
        DB_URI: ${{ secrets.DB_URI }}
      run: go test -v ./...
